language: ruby

services:
  - docker

before_install:
  - RUNTIME_BASE_IMAGE_NAME=ubuntu:bionic \
    RUNTIME_IMAGE_NAME=projectzetton/zetton-docker:ubuntu18.04-runtime \
    ./script/build_runtime.sh
  - RUNTIME_BASE_IMAGE_NAME=nvcr.io/nvidia/tensorrt:20.03-py3 \
    RUNTIME_IMAGE_NAME=projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-runtime \
    ./script/build_runtime.sh
  - RUNTIME_BASE_IMAGE_NAME=nvcr.io/nvidia/deepstream-l4t:5.0-20.07-base \
    RUNTIME_IMAGE_NAME=projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-jetson-runtime \
    ./script/build_runtime.sh
  - RUNTIME_IMAGE_NAME=projectzetton/zetton-docker:ubuntu18.04-runtime \
    DEVEL_IMAGE_NAME=projectzetton/zetton-docker:ubuntu18.04-devel \
    ./script/build_devel.sh
  - RUNTIME_IMAGE_NAME=projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-runtime \
    DEVEL_IMAGE_NAME=projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-devel \
    ./script/build_devel.sh
  - RUNTIME_IMAGE_NAME=projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-jetson-runtime \
    DEVEL_IMAGE_NAME=projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-jetson-devel \
    ./script/build_devel.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push projectzetton/zetton-docker:ubuntu18.04-runtime
  - docker push projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-runtime
  - docker push projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-jetson-runtime
  - docker push projectzetton/zetton-docker:ubuntu18.04-devel
  - docker push projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-devel
  - docker push projectzetton/zetton-docker:cuda10.2-cudnn7-trt7.0.0-ubuntu18.04-jetson-devel

script:
  - bundle exec rake test
