#!/usr/bin/env bash

set -x

RUNTIME_BASE_IMAGE_NAME=${RUNTIME_BASE_IMAGE_NAME:-nvcr.io/nvidia/tensorrt:20.11-py3}
RUNTIME_IMAGE_NAME=${RUNTIME_IMAGE_NAME:-projectzetton/zetton-docker:cuda11.1-cudnn8-trt7.2.1-opencv4.5.2-ubuntu18.04-runtime}
RUNTIME_IMAGE_NUM_THREADS=${RUNTIME_IMAGE_NUM_THREADS:-4}
RUNTIME_IMAGE_USE_MIRROR=${RUNTIME_IMAGE_USE_MIRROR:-true}
RUNTIME_IMAGE_ROS_DISTRO=${RUNTIME_IMAGE_ROS_DISTRO:-melodic}
RUNTIME_IMAGE_CMAKE_VERSION=${RUNTIME_IMAGE_CMAKE_VERSION:-3.20.2}
RUNTIME_IMAGE_OPENCV_VERSION=${RUNTIME_IMAGE_OPENCV_VERSION:-4.5.2}
RUNTIME_IMAGE_ABSL_VERSION=${RUNTIME_IMAGE_ABSL_VERSION:-lts_2021_11_02}

docker build \
  -t "${RUNTIME_IMAGE_NAME}" \
  -f Dockerfile \
  --build-arg BASE_IMAGE="${RUNTIME_BASE_IMAGE_NAME}" \
  --build-arg NUM_THREADS="${RUNTIME_IMAGE_NUM_THREADS}" \
  --build-arg USE_MIRROR=${RUNTIME_IMAGE_USE_MIRROR} \
  --build-arg BUILD_ON_ARM=${RUNTIME_IMAGE_BUILD_ON_ARM} \
  --build-arg ROS_DISTRO=${RUNTIME_IMAGE_ROS_DISTRO} \
  --build-arg CMAKE_VERSION=${RUNTIME_IMAGE_CMAKE_VERSION} \
  --build-arg OPENCV_VERSION=${RUNTIME_IMAGE_OPENCV_VERSION} \
  --build-arg ABSL_VERSION=${RUNTIME_IMAGE_ABSL_VERSION} \
  .
