#!/usr/bin/env bash

set -x

export RUNTIME_BASE_IMAGE_NAME=${RUNTIME_BASE_IMAGE_NAME:-arm64v8/ubuntu:bionic}
export RUNTIME_IMAGE_NAME=${RUNTIME_IMAGE_NAME:-projectzetton/zetton-docker:ubuntu18.04-arm64v8-runtime}
export RUNTIME_IMAGE_NUM_THREADS=${RUNTIME_IMAGE_NUM_THREADS:-8}
export RUNTIME_IMAGE_USE_MIRROR=${RUNTIME_IMAGE_USE_MIRROR:-true}
export RUNTIME_IMAGE_BUILD_ON_ARM=true
export RUNTIME_IMAGE_ROS_DISTRO=${RUNTIME_IMAGE_ROS_DISTRO:-melodic}
export RUNTIME_IMAGE_CMAKE_VERSION=${RUNTIME_IMAGE_CMAKE_VERSION:-3.20.2}
export RUNTIME_IMAGE_OPENCV_VERSION=${RUNTIME_IMAGE_OPENCV_VERSION:-4.5.2}
export RUNTIME_IMAGE_ABSL_VERSION=${RUNTIME_IMAGE_ABSL_VERSION:-lts_2021_11_02}
export DEVEL_IMAGE_NAME=${DEVEL_IMAGE_NAME:-projectzetton/zetton-docker:ubuntu18.04-arm64v8-devel}
export DEVEL_IMAGE_ROS_DISTRO=${DEVEL_IMAGE_ROS_DISTRO:-melodic}

./script/build_runtime.sh
./script/build_devel.sh
